name: delta_docs
channels:
  - defaults
dependencies:
  - ca-certificates=2023.08.22=hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_0
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.11=h1a28f6b_2
  - pip=23.2.1=py38hca03da5_0
  - python=3.8.18=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=68.0.0=py38hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - tk=8.6.12=hb8d0fd4_0
  - wheel=0.41.2=py38hca03da5_0
  - xz=5.4.2=h80987f9_0
  - zlib=1.2.13=h5a0b063_0
  - pip:
      - alabaster==0.7.13
      - babel==2.13.0
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - colorama==0.4.6
      - docutils==0.15.2
      - idna==3.4
      - imagesize==1.4.1
      - jinja2==2.11.3
      - livereload==2.6.3
      - markupsafe==2.0.0
      - packaging==23.2
      - py4j==0.10.9.7
      - pygments==2.16.1
      - pyspark==3.5.0
      - pytz==2023.3.post1
      - requests==2.31.0
      - six==1.16.0
      - snowballstemmer==2.2.0
      - sphinx==2.0.1
      - sphinx-autobuild==2021.3.14
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tornado==6.3.3
      - urllib3==2.0.6
prefix: <home>/anaconda3/envs/delta_docs
