name: "Delta Connectors"
on: [push, pull_request]
jobs:
  build:
    name: "DC: Scala ${{ matrix.scala }}"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # These Scala versions must match those in the build.sbt
        scala: [2.13.13]
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache Scala, SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2
            ~/.cache/coursier
            ~/.m2
          key: build-cache-3-with-scala_${{ matrix.scala }}
      - name: Run Scala Style tests on test sources (Scala 2.13 only)
        run: build/sbt "++ ${{ matrix.scala }}" testScalastyle
        if: startsWith(matrix.scala, '2.13.')
      - name: Run sqlDeltaImport tests (Scala 2.13 only)
        run: build/sbt "++ ${{ matrix.scala }}" sqlDeltaImport/test
        if: ${{ !startsWith(matrix.scala, '2.11.') }}
        # These tests are not working yet
        # - name: Run Delta Standalone Compatibility tests (Scala 2.12 only)
        #  run: build/sbt "++ ${{ matrix.scala }}" compatibility/test
        #  if: startsWith(matrix.scala, '2.12.')
      - name: Run Delta Standalone tests
        run: build/sbt "++ ${{ matrix.scala }}" standalone/test testStandaloneCosmetic/test standaloneParquet/test testParquetUtilsWithStandaloneCosmetic/test
