name: Add new pull requests to Backlog (External)

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  automate-new-pull-requests:
    if: ${{ !contains('allisonport-db dennyglee scottsand-db tdas zsxwing', github.event.sender.login) }}
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: oss-delta-prs
          column: Needs Review
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION_TOKEN }}
