name: "Delta Lake Connectors Tests"
on: [push, pull_request]
jobs:
  build:
    name: "Run tests"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        scala: [2.13.8, 2.12.8, 2.11.12]
    steps:
      - uses: actions/checkout@v2
      - name: install java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Cache Scala, SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
            ~/.cache/coursier
            ~/.m2
          key: build-cache-3-with-scala_${{ matrix.scala }}
      - name: Run Scala Style tests on test sources (Scala 2.12 only)
        run: build/sbt "++ ${{ matrix.scala }}" testScalastyle
        if: startsWith(matrix.scala, '2.12.')
      - name: Run sqlDeltaImport tests (Scala 2.12 and 2.13 only)
        run: build/sbt "++ ${{ matrix.scala }}" sqlDeltaImport/test
        if: ${{ !startsWith(matrix.scala, '2.11.') }}
      - name: Run Delta Standalone Compatibility tests (Scala 2.12 only)
        run: build/sbt "++ ${{ matrix.scala }}" compatibility/test
        if: startsWith(matrix.scala, '2.12.')
      - name: Run Delta Standalone tests
        run: build/sbt "++ ${{ matrix.scala }}" standalone/test testStandaloneCosmetic/test standaloneParquet/test testParquetUtilsWithStandaloneCosmetic/test
      - name: Run Hive 3 tests
        run: build/sbt "++ ${{ matrix.scala }}" hiveMR/test hiveTez/test
      - name: Run Hive 2 tests
        run: build/sbt "++ ${{ matrix.scala }}" hive2MR/test hive2Tez/test
      - name: Run Flink tests (Scala 2.11 and 2.12 only)
        run: build/sbt -mem 3000 "++ ${{ matrix.scala }}" flink/test
        if: ${{ !startsWith(matrix.scala, '2.13.') }}
